In [10]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori , association_rules

In [11]:
df = pd.read_csv("Grocery_Dataset.csv")

In [12]:
df.head(
)

  TransactionID CustomerID        Date  ... UnitPrice TotalAmount PaymentMethod
0     TXN100001  CUST00314  2025-03-16  ...    123.36      123.36           UPI
1     TXN100001  CUST00314  2025-03-16  ...     40.33       40.33           UPI
2     TXN100001  CUST00314  2025-03-16  ...     81.05      162.10           UPI
3     TXN100001  CUST00314  2025-03-16  ...     26.43       52.86           UPI
4     TXN100001  CUST00314  2025-03-16  ...     53.01      106.02           UPI

[5 rows x 11 columns]

In [13]:
transactions = df.groupby('TransactionID')['Item'].apply(list).tolist()

In [14]:
#we now performing the Transaction Encoding and then again to the dataframe for the apriori algo
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)

In [16]:
encoded_df = pd.DataFrame(te_array , columns = te.columns_)
encoded_df.head()

   Apples  Bananas  Biscuits  Bread  ...    Tea  TomatoSauce  Tomatoes  Yogurt
0   False    False      True   True  ...   True         True     False   False
1    True    False     False   True  ...  False        False     False   False
2   False    False     False  False  ...  False        False     False   False
3   False    False      True   True  ...  False        False     False   False
4   False    False     False   True  ...  False        False     False   False

[5 rows x 24 columns]

In [17]:
frequent_itemsets = apriori(
    encoded_df,
    min_support = 0.4,
    use_colnames = True
)

In [18]:
frequent_itemsets

     support               itemsets
0   0.651176                (Bread)
1   0.654824               (Butter)
2   0.647294                 (Eggs)
3   0.649294                 (Milk)
4   0.532353        (Bread, Butter)
5   0.527882          (Eggs, Bread)
6   0.530941          (Bread, Milk)
7   0.528353         (Eggs, Butter)
8   0.528706         (Milk, Butter)
9   0.527412           (Eggs, Milk)
10  0.452118  (Eggs, Bread, Butter)
11  0.453059  (Bread, Milk, Butter)
12  0.451882    (Eggs, Bread, Milk)
13  0.451412   (Eggs, Milk, Butter)

In [19]:
rules = association_rules(
    frequent_itemsets,
    metric = 'confidence',
    min_threshold = 0.6
)

In [20]:
rules

        antecedents      consequents  ...  certainty  kulczynski
0           (Bread)         (Butter)  ...   0.471357    0.815248
1          (Butter)          (Bread)  ...   0.463831    0.815248
2            (Eggs)          (Bread)  ...   0.471141    0.813091
3           (Bread)           (Eggs)  ...   0.463177    0.813091
4           (Bread)           (Milk)  ...   0.473510    0.816539
5            (Milk)          (Bread)  ...   0.477445    0.816539
6            (Eggs)         (Butter)  ...   0.467660    0.811556
7          (Butter)           (Eggs)  ...   0.452414    0.811556
8            (Milk)         (Butter)  ...   0.461950    0.810840
9          (Butter)           (Milk)  ...   0.450828    0.810840
10           (Eggs)           (Milk)  ...   0.471907    0.813540
11           (Milk)           (Eggs)  ...   0.467786    0.813540
12    (Eggs, Bread)         (Butter)  ...   0.584196    0.773458
13   (Eggs, Butter)          (Bread)  ...   0.586357    0.775010
14  (Bread, Butter)           (Eggs)  ...   0.572680    0.773878
15           (Eggs)  (Bread, Butter)  ...   0.355226    0.773878
16          (Bread)   (Eggs, Butter)  ...   0.351865    0.775010
17         (Butter)    (Eggs, Bread)  ...   0.344320    0.773458
18    (Bread, Milk)         (Butter)  ...   0.575037    0.772596
19  (Bread, Butter)           (Milk)  ...   0.575284    0.774411
20   (Milk, Butter)          (Bread)  ...   0.589822    0.776337
21          (Bread)   (Milk, Butter)  ...   0.354446    0.776337
22           (Milk)  (Bread, Butter)  ...   0.353725    0.774411
23         (Butter)    (Bread, Milk)  ...   0.343109    0.772596
24    (Eggs, Bread)           (Milk)  ...   0.589481    0.775994
25     (Eggs, Milk)          (Bread)  ...   0.589455    0.775370
26    (Bread, Milk)           (Eggs)  ...   0.577826    0.774603
27           (Eggs)    (Bread, Milk)  ...   0.356392    0.774603
28          (Bread)     (Eggs, Milk)  ...   0.352391    0.775370
29           (Milk)    (Eggs, Bread)  ...   0.356007    0.775994
30     (Eggs, Milk)         (Butter)  ...   0.582533    0.772632
31   (Eggs, Butter)           (Milk)  ...   0.584767    0.774805
32   (Milk, Butter)           (Eggs)  ...   0.585505    0.775594
33           (Eggs)   (Milk, Butter)  ...   0.357902    0.775594
34           (Milk)   (Eggs, Butter)  ...   0.353828    0.774805
35         (Butter)     (Eggs, Milk)  ...   0.342692    0.772632

[36 rows x 14 columns]