In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [6]:

df = pd.read_csv("sample_data/Loan_Approval_Dataset.csv")

In [7]:
df.head()

   loan_id   no_of_dependents  ...  bank_asset_value  loan_status
0        1                  2  ...           8000000     Approved
1        2                  0  ...           3300000     Rejected
2        3                  3  ...          12800000     Rejected
3        4                  3  ...           7900000     Rejected
4        5                  5  ...           5000000     Rejected

[5 rows x 13 columns]

In [8]:
df.describe()

           loan_id   no_of_dependents  ...   luxury_assets_value   bank_asset_value
count  4269.000000        4269.000000  ...          4.269000e+03       4.269000e+03
mean   2135.000000           2.498712  ...          1.512631e+07       4.976692e+06
std    1232.498479           1.695910  ...          9.103754e+06       3.250185e+06
min       1.000000           0.000000  ...          3.000000e+05       0.000000e+00
25%    1068.000000           1.000000  ...          7.500000e+06       2.300000e+06
50%    2135.000000           3.000000  ...          1.460000e+07       4.600000e+06
75%    3202.000000           4.000000  ...          2.170000e+07       7.100000e+06
max    4269.000000           5.000000  ...          3.920000e+07       1.470000e+07

[8 rows x 10 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4269 non-null   int64
 1    no_of_dependents          4269 non-null   int64
 2    education                 4269 non-null   object
 3    self_employed             4269 non-null   object
 4    income_annum              4269 non-null   int64
 5    loan_amount               4269 non-null   int64
 6    loan_term                 4269 non-null   int64
 7    cibil_score               4269 non-null   int64
 8    residential_assets_value  4269 non-null   int64
 9    commercial_assets_value   4269 non-null   int64
 10   luxury_assets_value       4269 non-null   int64
 11   bank_asset_value          4269 non-null   int64
 12   loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB

In [10]:
#starting with the preprocessing part like replacing missing value with mode
df.isnull().sum()

loan_id                      0
 no_of_dependents            0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

In [12]:
df.fillna(df.mode().iloc[0],inplace = True)

In [14]:
#now we will be doing the label encoding
le = LabelEncoder()

for column in df.select_dtypes(include = 'object').columns:
  df[column] = le.fit_transform(df[column])

In [15]:
df.head()

   loan_id   no_of_dependents  ...   bank_asset_value   loan_status
0        1                  2  ...            8000000             0
1        2                  0  ...            3300000             1
2        3                  3  ...           12800000             1
3        4                  3  ...            7900000             1
4        5                  5  ...            5000000             1

[5 rows x 13 columns]

In [24]:
#now we will do the train_test_split
X = df.drop(' loan_status',axis = 1)
y = df[' loan_status']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [22]:
print(df.columns)

Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [26]:
#decision tree model making
dt_model = DecisionTreeClassifier(random_state = 42)

dt_model.fit(X_train,y_train);

In [28]:
y_pred_dt = dt_model.predict(X_test)

In [29]:
print("Decision Tree Accuracy : " , accuracy_score(y_test,y_pred_dt))
print(confusion_matrix(y_test,y_pred_dt))
print(classification_report(y_test,y_pred_dt))

Decision Tree Accuracy :  0.9742388758782201
[[524  12]
 [ 10 308]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       536
           1       0.96      0.97      0.97       318

    accuracy                           0.97       854
   macro avg       0.97      0.97      0.97       854
weighted avg       0.97      0.97      0.97       854

In [32]:
#feature scaling for the KNN
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [34]:
knn_model = KNeighborsClassifier(n_neighbors = 5)

knn_model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [35]:
y_pred_knn = knn_model.predict(X_test_scaled)

In [36]:
print("KNN results : ",accuracy_score(y_test , y_pred_knn))
print(confusion_matrix(y_test,y_pred_knn))
print(classification_report(y_test,y_pred_knn))

KNN results :  0.8805620608899297
[[479  57]
 [ 45 273]]
              precision    recall  f1-score   support

           0       0.91      0.89      0.90       536
           1       0.83      0.86      0.84       318

    accuracy                           0.88       854
   macro avg       0.87      0.88      0.87       854
weighted avg       0.88      0.88      0.88       854